#!/bin/sh

PATH=/bin:/usr/bin
export PATH

download_url=https://factorio.com/get-download/stable/headless/linux64

cd /opt

if [ "$(curl -I -L $download_url --silent | egrep '^ETag:')" != "$(cat factorio_headless.etag)" ] ; then
    systemctl stop factorio-headless.service
    curl -L $download_url --output factorio_headless.tar.xz --silent 
    curl -I -L $download_url --silent | egrep '^ETag:' > factorio_headless.etag
    if [ -f factorio_headless.tar.xz ] ; then
	tar Jxvf factorio_headless.tar.xz
    fi
    systemctl start factorio-headless.service
fi



